---
- fail: msg=Setting {{ item }} is not defined
  when: item not in hostvars[inventory_hostname]
  with_items:
  - license

- name: Include the installation
  include: install.yml

- name: Include Directadmin configuration
  include: configure.yml


- name: Include PHP extension configuration
  include: custombuild/phpextensions.yml

- name: Include Lets Encrypt
  include: letsencrypt.yml
  when: directadmin_lets_encrypt_host|default(true)
