---
- fail: msg=Setting {{ item }} is not defined
  when: item not in hostvars[inventory_hostname]
  with_items:
  - license

- include: install.yml
- include: configure.yml
- include: custombuild/phpextensions.yml
- include: resources/administrators.yml
