# This file is included in the install.yml, this makes
# sure that we have the correct configurations when
# installing this server.
---
# This is more resilient, but a lot slower to run. Undecided if this should be changed.
# Reporting changes has been disabled as build set always returns 0.
- name: DirectAdmin | Configure CustomBuild
  command:
    cmd: /usr/local/directadmin/custombuild/build set {{ item.key }} {{ item.value }}
  with_dict: "{{ directadmin_custombuild_options|default({}) }}"
  register: configure_custombuild
  changed_when: '"Changed" in configure_custombuild.stdout'

- name: DirectAdmin | Create CustomBuild Custom Directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 755
  with_items:
    - /usr/local/directadmin/custombuild/custom
