---
- name: DirectAdmin | Configure PHP extensions
  lineinfile:
    path: /usr/local/directadmin/custombuild/options.conf
    regexp: "^php_{{ item.key }}="
    line: "php_{{ item.key }}={{ item.value }}"
  with_dict: "{{ directadmin_php_extensions|default({}) }}"
  notify:
    - rebuild php extensions
